### ISSUE TITLE
TabBar drop down button (>>) is not displayed when resizing the sidebar

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#2004]
STR: 
1. Open 2 tabs 
2. Resize the right sidebar until one of the tab is hidden

Expected result:
The tab is hidden and the drop down button (>>) is displayed

Actual result:
The tab is hidden, but the drop down button isn't displayed

GIF : 
![peek 13-02-2017 12-11](https://cloud.githubusercontent.com/assets/578107/22881187/be65409a-f1e5-11e6-836c-d262a94edc83.gif)

I guess we don't check if we should show the button when resizing the sidebars.

_Bug found by @princiya , thanks !_

**Comment by jasonLaster** [comment]
Hmm. Good catch. We do have an on resize check so it should work. I think @princiya is looking at this with her flex changes. It's most likely how we calculate hidden tabs

**Comment by jasonLaster** [comment]
i believe we fixed this with @princiya's work.

**Comment by princiya** [comment]
This isn't fixed yet. It works with window resize event, not CSS div resize. From the gif, it's a CSS div resize happening there. I was looking at this last week, but couldn't finish it up ;) Let me know the priority for this and I will get back to this soon :)

**Comment by jasonLaster** [comment]
Ahh. Thanks for clarifying. 

No pressure.

**Comment by jasonLaster** [comment]
@AnshulMalik is working on this

**Comment by jasonLaster** [comment]
one option


```diff
diff --git a/src/components/App.js b/src/components/App.js
index 3d4e53d..6c2d1db 100644
--- a/src/components/App.js
+++ b/src/components/App.js
@@ -79,6 +79,12 @@ class App extends Component {
     const { horizontal } = this.state;

     const overflowX = endPanelCollapsed ? "hidden" : "auto";
+    const onResize = (panel, size) => {
+      if (panel == "start") {
+        this.setState({startPanelSize: size})
+      }
+      this.setState({endPanelSize: size})
+    }

     return dom.div(
       { className: "debugger" },
@@ -88,6 +94,7 @@ class App extends Component {
         minSize: 10,
         maxSize: "50%",
         splitterSize: 1,
+        onResize,
         startPanel: Sources({ sources, horizontal }),
         startPanelCollapsed,
         endPanel: SplitBox({
@@ -96,6 +103,7 @@ class App extends Component {
           minSize: 10,
           maxSize: "80%",
           splitterSize: 1,
+          onResize,
           endPanelControl: true,
           startPanel: this.renderEditorPane(),
           endPanel: SecondaryPanes({ horizontal }),
```

**Comment by jasonLaster** [comment]
another option would use child context for splitter, which would be similar to how App uses context [here](https://github.com/devtools-html/debugger.html/blob/master/src/components/App.js#L46-L49). Except, children of splitter who care would listen to a panelSize context item...
