### ISSUE TITLE
[ObjectInspector] We should only style default window properties when viewing a window object

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2946]
We currently style window properties with a lighter shade of blue all the time.

We should only do this when viewing a window object

<img src='https://shipusercontent.com/e4885b6156dbcea152c023b4756bda7a/Screen%20Shot%202017-05-17%20at%205.47.32%20PM.png' title='Screen Shot 2017-05-17 at 5.47.32 PM.png' width=297>

**Comment by jbhoosreddy** [comment]
I was going through the object inspector code to see where this was coming from.. but still this is a pretty interesting bug (to find).

**Comment by jasonLaster** [comment]
@jbhoosreddy it certainly is:

https://github.com/devtools-html/debugger.html/blob/master/src/utils/object-inspector.js#L66-L69

Try running `yarn storybook` and going to preview :)

**Comment by jbhoosreddy** [comment]
fixed in #3099

**Comment by jasonLaster** [comment]
Still seeing this

<img src='https://shipusercontent.com/6c7f72bf68663b3251807d5f215dca7a/Screen%20Shot%202017-07-21%20at%2010.26.49%20AM.png' title='Screen Shot 2017-07-21 at 10.26.49 AM.png' width=598>

**Comment by jasonLaster** [comment]
@jbhoosreddy @nchevobbe i'm worried that to properly diagnose this, we need to know about the grip we're previewing which will change OI in a decently large way.

**Comment by nchevobbe** [comment]
What about having a `parent` property on the ObjectInspectorItem so we can retrieve it quickly ?
Also, it seems that we don't have `default-property` CSS class in devtools-reps, which I'll add.

This leads to another issue, when logging the window to the console, I don't want it to have this style applied. I see value having it in the scope, since it's always there, so I'll think of something to be able to enable/disable this behavior.

**Comment by jasonLaster** [comment]
that sounds good - i like having parent passed down to `renderItem`. I'll see what I can do with the `tree` component.

**Comment by nchevobbe** [comment]
I was thinking to do it directly in the `createNode` function, which would then return `{name, path, contents, parent}`.
This way we would have access to the parent item for each item (and not only in the renderItem function).
In fact, I am already experimenting with it for the "show set/map entries in OI".
I'll ping you on the PR so you can tell me how it feels.

**Comment by jasonLaster** [comment]
That would be even better!

**Comment by jasonLaster** [comment]
we can do this post release

**Comment by nchevobbe** [comment]
I'm wondering now if it would make more sense to only dim the `[default properties]` node when it is collapsed (as well as the `__proto__` one), and render it as a regular one when it is expanded.

The reason being that if you did expand the node, this means that you are probably interested in seeing what's inside, and having the node semi-transparent does not help.

As a bonus, it would be super easy to do :)

**Comment by jasonLaster** [comment]
Yes, i think that's the way to go.
