### ISSUE TITLE
[Breakpoints] width is set to 1px

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3383]
It looks like there is a race condition with the editor that occassionally sets breakpoints to a really small width:

![Pasted Image 1.tiff](https://shipusercontent.com/8d112d1551f659729970daf2416fee23/Pasted%20Image%201.tiff)

**Comment by jasonLaster** [comment]
This should be fixed by the editor.state bug

**Comment by codehag** [comment]
We have solved one part of the issue, associated with .wasm files. However we still have this issue when switching the panel orientation. This may be an issue in code mirror itself

STR:

- Open debugger while running in the panel
- Add a breakpoint while the debugger is in the bottom panel
- switch the debugger position to being a side panel
- Breakpoint will be a baby bps

Gif:
recordit.co/Luuhcd6uKu

CSS issues:
before Rerender
<img width="443" alt="screen shot 2017-07-24 at 11 14 56 am" src="https://user-images.githubusercontent.com/26968615/28516428-8141a44c-7061-11e7-830b-f2bde7bb4b0a.png">
After rerender
<img width="188" alt="screen shot 2017-07-24 at 11 13 47 am" src="https://user-images.githubusercontent.com/26968615/28516421-78f8cd56-7061-11e7-93f3-014dfbfd7cae.png">

**Comment by codehag** [comment]
Should now be fixed

**Comment by jasonLaster** [comment]
we can use this min-width fix if we need it: https://github.com/devtools-html/debugger.html/pull/3419

**Comment by jasonLaster** [comment]
I'm re-opening this issue because we're seeing breakpoints collapse to 1px when the layout changes from horizontal to vertical.

**Comment by jasonLaster** [comment]
@yurydelendik added a weakmap here that keeps us from doing unnecessary updates:

https://github.com/devtools-html/debugger.html/pull/3764/commits/c308ceb2851d561b9987d70aa42a2c5cbce887b0

we might want to revisit later.
