### ISSUE TITLE
[Expressions] Removed watched expressions reappear

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3598]
#### STR

1. Go to http://www.example.org/
2. Open the debugger
3. Make sure it is set to "Ignore exceptions"
4. Add a new watched expression: "foo.bar" (without quotes)
5. Set the debugger to "Pause on uncaught exceptions"
6. The debugger pauses: "ReferenceError: foo is not defined"
7. Remove the watched expression
8. Click ▷ (Resume)

Expected: the watched expression stays removed.
Result: the watched expression reappears.
From: https://bugzilla.mozilla.org/show_bug.cgi?id=1388099

**Comment by nyrosmith** [comment]
Maybe related to #3597 ?

**Comment by jasonLaster** [comment]
Yeah, that's a great point

**Comment by jasonLaster** [comment]
This was fixed when we fixed #4106

**Comment by Loirooriol** [comment]
The underlying problem is not fixed. Just a small change at step 5:

1. Go to http://www.example.org/
2. Open the debugger
3. Make sure it is set to "Ignore exceptions"
4. Add a new watched expression: "foo.bar" (without quotes)
5. Set the debugger to "Pause on all exceptions"
6. The debugger pauses: "ReferenceError: foo is not defined"
7. Remove the watched expression
8. Click ▷ (Resume)

**Comment by lukaszsobek** [comment]
Re-opening.

**Comment by darkwing** [comment]
Can no longer reproduce.
