### ISSUE TITLE
TypeError: debuggerClient.mainRoot.getFront is not a function

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#6890]
1) Load `localhost:8000`
2) Click on an existing tab in the list
3) Open the Browser Console and see the following exception:
`TypeError: debuggerClient.mainRoot.getFront is not a function`

The page stays empty after the click.
Honza

**Comment by janodvarko** [comment]
A workaround for anyone being blocked by this issue:

```js
diff --git a/src/client/firefox/commands.js b/src/client/firefox/commands.js
index 322e6f5..ce9d065 100644
--- a/src/client/firefox/commands.js
+++ b/src/client/firefox/commands.js
@@ -364,6 +364,10 @@ async function checkServerSupportsListWorkers() {
     return false;
   }
 
+  if (!debuggerClient.mainRoot.getFront) {
+    return false;
+  }
+
   const deviceFront = await debuggerClient.mainRoot.getFront("device");
   const description = await deviceFront.getDescription();
```

**Comment by jasonLaster** [comment]
this was fixed here - https://github.com/devtools-html/debugger.html/pull/6887

it should be available on master now.

**Comment by janodvarko** [comment]
I fetched the master and I can see the commit on my machine (the one introducing `debuggerClient.mainRoot.getFront` call). I also have the latest m-c and I am still experiencing the problem.

Honza
