### ISSUE TITLE
Resize cursor and splitter position are shifted when the bookmarks sidebar is opened and dragging splitter

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#856]
Regression range:
https://hg.mozilla.org/integration/fx-team/pushloghtml?fromchange=500496dfefccc73d1f87ff912563a8ee1afe8e91&tochange=cdbfde37e79590e4c188ba854ab0b1612402e338

**Comment by wldcordeiro** [comment]
Since the SplitBox comes from m-c could it be a fix applied upstream @jlongster @jasonLaster? Or maybe our usage of it is wrong.

**Comment by magicp-github** [comment]
This bug still reproduce in latest Nightly Build ID (20161012030211)

**Comment by jasonLaster** [comment]
@magicp-github should be fixed when we update the debugger on nightly soon. Sorry, there's some lag between a patch landing on github and being shown in nightly

**Comment by magicp-github** [comment]
Hello @jasonLaster,
This bug still reproduce in latest Nightly build (20161111030203). Any update?

**Comment by jasonLaster** [comment]
I'll look into this on monday

**Comment by jasonLaster** [comment]
This is a dupe of #1378
